### ISSUE TITLE
Installing via Xcode 11 breaks compiling my tests.

### ISSUE THREAD

**Issue by crayment** [swift-aws/aws-sdk-swift#167]
**Describe the bug**
I have used Xcode 11 beta 7 to install this into a Mac app via the new swift package features. It works great in my main app target, however after installing I can no longer compile my tests. They fail with the  error `missing required module 'CNIOAtomics'`

**To Reproduce**
1. In a new macOS project in the Xcode 11 beta do: File -> Swift Package -> Add Package Dependency
2. Paste in `https://github.com/swift-aws/aws-sdk-swift-core/issues/34` and tick all of `["S3", "SES", "CloudFront", "ELBV2", "IAM", "Kinesis"]`
3. Try to build your test suite that is hosted by your app

**Expected behavior**
Expect to be able to compile my tests

**Setup (please complete the following information):**
 - OS: 10.14.5 
 - Version of aws-sdk-swift: 3.1.0
 - Authentication mechanism: hard-coded credentials

**Additional context**

There is a similar issue reported on the [core repo here](https://github.com/swift-aws/aws-sdk-swift-core/issues/34)

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/78082/64059883-ce11bf00-cb81-11e9-8730-ce91e00d0276.png">

**Comment by adam-fowler** [comment]
I’ve included aws-sdk-swift in XCode 10 projects before and experienced similar issues, but with CNIOpenSSL. These were resolved when upgrading to Swift NIO 2.0. That code path is not on the master branch though. 

I haven’t looked at XCode 11 yet so don’t know much about their SPM support. If you could try our nio2.0 branch and see if that works that’d be helpful. Unfortunately there are api changes to the EventLoopFuture class with nio2.0 which will mean you might need to make changes to your code first. 

If that doesn’t work you could try the code from repository aws-sdk-appleos which is the equivalent of this repository but links with NIOTransportServices to allow support for all Apple platforms.

**Comment by crayment** [comment]
Thanks for the suggestions!

Unfortunately both the `nio2.0` branch on this repo and `https://github.com/swift-aws/aws-sdk-appleos` both result in the same error when compiling tests.

**Comment by adam-fowler** [comment]
Do you have CNIOAtomics plus all the other NIO and AWS libs in your 'Embedded Binaries' section of your main app settings?

Also what happens if you do this the old school method where you generate the xcodeproj for aws-sdk-swift using `swift package generate-xcodeproj`, manually include that xcodeproj file into your main app file and include all the targets from the generated xcodeproj in your 'Embedded Binaries' for the main app.

**Comment by crayment** [comment]
I actually pruned my embedding down to just S3 as that's all I'm using directly. Here is a screen:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/78082/64069690-12e23800-cc0c-11e9-9e74-1c4d471ad1d8.png">

With this my main app still runs fine and tests still fail with the same error. I don't see anywhere to add `CNIOAtomics` to my embedded binaries, it doesn't show up in this list:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/78082/64069704-4b821180-cc0c-11e9-91fd-c40e45785436.png">

I'll try going the more traditional swift package route and report back.

**Comment by crayment** [comment]
The old school method works! I had to add all of these to the embedded content: 

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/78082/64069868-8c7c2500-cc10-11e9-945f-7ee0dfcf1b6a.png">

Thanks for the help! I can move forward with this :)

**Comment by adam-fowler** [comment]
I reported this to Apple. Let’s see what happens. Would be most frustrated if people can’t use the XCode 11 SPM features with this lib.

**Comment by adam-fowler** [comment]
@crayment https://github.com/apple/swift-nio/issues/1128

**Comment by crayment** [comment]
@adam-fowler Thanks for following up! Adding some module maps to my "Other Swift Flags" as described in the workaround made everything happy 😄 

Here are my flags and some screens for completeness. Note I switched to the apple repo since I don't need to support linux, but I imagine a similar setup would work on this repo.

```
-Xcc
-fmodule-map-file=$(PROJECT_TEMP_ROOT)/GeneratedModuleMaps/macosx/CNIOAtomics.modulemap
-Xcc
-fmodule-map-file=$(PROJECT_TEMP_ROOT)/GeneratedModuleMaps/macosx/CNIODarwin.modulemap
-Xcc
-fmodule-map-file=$(PROJECT_TEMP_ROOT)/GeneratedModuleMaps/macosx/CNIOLinux.modulemap
-Xcc
-fmodule-map-file=$(PROJECT_TEMP_ROOT)/GeneratedModuleMaps/macosx/CNIOHTTPParser.modulemap
```

<img width="954" alt="image" src="https://user-images.githubusercontent.com/78082/64210324-30a7db00-ce60-11e9-820d-556e5f199f88.png">

<img width="950" alt="image" src="https://user-images.githubusercontent.com/78082/64210297-22f25580-ce60-11e9-804e-43e02769496d.png">

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/78082/64210386-57661180-ce60-11e9-91f6-1b840d33c5b4.png">

**Comment by adam-fowler** [comment]
This is now resolved in XCode 11.2
